# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto report script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,9,10 * * *"

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Upgrade pip
      run: 
        python -m pip install --upgrade pip
    - name: Install dependencies
      run:
        pip install -r requirements.txt
    - name: Report
      run:
        python main.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} -o ${{ secrets.LONGITUDE }} -a ${{ secrets.LATITUDE }} -s ${{ secrets.SCKEY }}
